services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"   # Local:Container
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    #Currently unneeded environment variables which are currently handled in Spring Boot
    # environment:
    #   SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/snowcoachdb
    #   SPRING_DATASOURCE_USERNAME: aaron
    #   SPRING_DATASOURCE_PASSWORD: pass
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: snowcoachdb
      POSTGRES_USER: aaron
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aaron -d snowcoachdb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
