version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"   # Local:Container
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/snowcoachdb
      SPRING_DATASOURCE_USERNAME: aaron
      SPRING_DATASOURCE_PASSWORD: pass
    depends_on:
      - db

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: snowcoachdb
      POSTGRES_USER: aaron
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
